### ISSUE TITLE
Disable discovery and server?

### ISSUE THREAD

**Issue by hspaay** [WebThingsIO/webthing-node#141]
Hi, just getting started and please forgive my ignorance if the question doesn't make sense.

webthing-node starts a server that can be discovered and connected to. However there are a few reasons why this is not always desirable:
1. No centralized permission management. Permissions need to be set per instance.
2. A network with VLANs doesn't allow for discovery
3. The current approach only works on fully trusted networks. In case of remote IoT devices such a network might not be available. 
4. Security concerns.  Minimizing attack footprint by only allowing access to a gateway. 

In theory, is it possible to turn off the server completely and configure it to push the discovery and status updates to a gateway?
(even if it requires an update to the gateway). This allows a single point for contact and authentication for all instances by the end user.
Thanks

**Comment by mrstegeman** [comment]
Just to clarify, do you want to disable both the web server and the mDNS server?

**Comment by hspaay** [comment]
Yes, for these use cases receiving anything from the local network is undesirable. That makes publishing mDNS discovery unnecessary. 
As a side note, webthing-node will need a plugin to publish the discovery info to a web service or to the gateway for this to be useful. Not sure if the current gateway supports this already but that is a different topic (and a chicken-egg problem)

**Comment by mrstegeman** [comment]
If there’s no web server, then there is no web thing API, and thus no way to “push” anything to the gateway. It sounds like what you want is just an adapter add-on for the gateway.

**Comment by hspaay** [comment]
@mrstegeman Ah interesting, what I had in mind (possibly incorrect) is to use the webthing-node library to push data into the gateway, without running as a server. For this the gateway would be a server and expose a standards based API that webthing-node implements. This model is similar to that of the FiWare context broker.  

If I understand you correctly, this is not the purpose of webthing-node and out of scope. 
So if I implement an add-on for the gateway, would this be re-usable by other gateway implementations? Is the internal gateway API standardized as part of WoT? The concern I have is that the addon is implementation specific to the gateway implementation and not reusable.

If so, would it be useful to have an open API for pushing data into the gateway to allow for multiple gateway implementations?  One issue I have with the gateway is that it does two things, the data aggregation and the presentation. (maybe the presentation is a plugin too, in that case this is incorrect)  

Thank you kindly for explanation.

**Comment by hspaay** [comment]
I'll close the issue since you answered the question.
Many thanks @mrstegeman

**Comment by benfrancis** [comment]
Hi @hspaay, as @mrstegeman explained, having devices acting as web servers (or being proxied to a web server using a gateway) is fundamentally how WebThings (and by my understanding the Web of Things in general) works. If a thing doesn't have a web URL then it isn't a web thing.

However, requiring that all Web of Things devices expose a web server to the Internet does have its downsides, as you have identified.

A couple of people have suggested the idea that the webthing WebSocket sub-protocol could _also_ work the other way around, i.e. the device acts as a client which opens up a WebSocket to a web service hosted elsewhere. The same messages would be sent back and forth, but the WebSocket would be opened up in the other direction. This would have benefits for a lot of use cases where traversing a firewall is not desirable or convenient and would make it much easier to deploy those devices.

Although not the original intended purpose, you might want to suggest this as a use case of the Web Thing Protocol, in response to the current [call for use cases and requirements](https://www.w3.org/community/web-thing-protocol/2020/07/06/call-for-use-cases-requirements-web-thing-protocol/).

**Comment by hspaay** [comment]
@benfrancis @mrstegeman looks like we are getting to the crux of the matter. I realize this is out of scope for webthing-node, so I posted a separate issue for this at https://github.com/w3c/wot-security/issues/197.

That said, probably good to clarify something. I realize in order to communicate with an appliance there has to be a server and client role. The architecture document has plenty of examples. This applies to the data flow however and does not require that the appliance listens for commands on an open port. 
As Ben pointed out, the WebSocket sub-protocol lets the data flow go either way, independent of the connection control. FiWare has support for MQTT as a notification channel. Either way there is no need to run a web server.  If the discovery process is reversed, the appliance discovers the gateway and connects to it and the gateway sends commands over WebSocket we can disable the server on the appliance. What is most unfortunate is that currently there is no spec or API (that I'm aware of) that supports this approach. As a security conscientious developer I am forced to create an insecure solution to remain compatible. 

Also please note that you cannot assume the LAN is safe. For example, your web browser runs code (javascript, wasm) that is downloaded from the internet and you have no control over it. There are [plenty examples](https://github.com/joevennix/lan-js) how to probe devices on the LAN from JavaScript so sooner or later someone will figure out how to connect to WoT appliances and take over control. 

Ben, I'm sure we can come up with a solution to the discoverability or link-ability that is more secure. For example, an unlinked device can still run a web server that is disabled when linking is established.  A reset can unlink it again. My main issue is that if I want to improve security by disabling listening ports, currently there is now way to do so. I think WoT has a responsibility to establish and push for best practices that are secure.

Ben thanks for the link, this is great.
