### ISSUE TITLE
Forbidden error when accessing the custom webthing from internet

### ISSUE THREAD

**Issue by apvenkat** [WebThingsIO/webthing-node#142]
Hi, 
The webthing module is working fine in localhost but when I try to access the webthing from internet I am getting forbidden error ( assume that I am running a webthing in public cloud ) , can anyone help in this issue ?

**Comment by mrstegeman** [comment]
Also answered here: https://discourse.mozilla.org/t/403-forbidden-error-when-accessing-the-webthing-webthing-node-via-nginx-reverse-proxy-or-from-public-cloud/72631

> You need to make sure you provide the right `hostname` argument when creating your `WebThingServer` instance.
>
> https://github.com/WebThingsIO/webthing-node/blob/master/lib/server.ts#L683
