### ISSUE TITLE
Types for Typescript

### ISSUE THREAD

**Issue by wwahammy** [WebThingsIO/webthing-node#88]
Typescript types would make this library easier to use from Typescript. I'd be happy to create a PR to add types to this repo if it's welcome. Otherwise, I can maintained them locally or submit them to DefinitelyTyped.

**Comment by mrstegeman** [comment]
I'd welcome a PR to this repo. 😃

**Comment by ericschultz** [comment]
Sounds good, I'm finishing up one project in the next few nights then I'll move on to this.

**Comment by ericschultz** [comment]
I've begun work on this at #91

**Comment by mrstegeman** [comment]
Closed by #138
